### ISSUE TITLE
Data incomplete in Eastern-Massachusetts

### ISSUE THREAD

**Issue by chkwon** [bstabler/TransportationNetworks#10]
@jingzbu

In [`EMA_net.tntp`](https://github.com/bstabler/TransportationNetworks/blob/master/Eastern-Massachusetts/EMA_net.tntp), `Free Flow Time`, `B`, and `Power` are all zeroes now. These values need to be identified in the data file. 

Also, `Type` needs to be integers, I believe.

**Comment by jingzbu** [comment]
@chkwon 
The Free Flow Time are positive; please see the correct column. The cost function is specified in EMA_intro.pdf. The Type plays no essential role and I just put a zero value.

**Comment by chkwon** [comment]
I understand that the PDF file contains information, but computer codes usually don't read PDF files; only read TNTP data file. Anyway, you need to specify all values to follow the consistent format of TNTP.

I don't understand what role `Type` plays, but in all other TNTP data files, `Type` columns are integers like 1 or 9, instead of 0.00000.  This format inconsistency makes reading and parsing data files rather difficult. If you want to put zero, please use 0, not 0.00000.

**Comment by jingzbu** [comment]
@chkwon 
Have updated and created a pull request. You can use the typical BPR cost function for testing. The one estimated by inverseVI is a bit tedious and can be cited for purposes of writing a paper.

**Comment by chkwon** [comment]
Thanks!
