### ISSUE TITLE
units for the chicago example

### ISSUE THREAD

**Issue by bstabler** [bstabler/TransportationNetworks#12]
I see in the chicago regional folder that it says about units: "Time: Minutes Distance: miles"
Should I then make these inferences about units:
In the network file:
+ capacity is in vehicle/minute
+ speed is in miles/minute 
and in the nodes file
+  x and y are in miles ?

Clearly that last one can't be right: x=712,000 miles!
But even the capacity and speeds give me exorbitant values with those assumptions. 
What units should I assume for these values?

**Comment by bargera** [comment]
As far as I know capacity in the Chicago Regional network is in vehicles/hour. The same is true regarding OD flows. 
Speed is probably in miles per hour. 
x and y in the nodes file are in feet.

Hillel
