### ISSUE TITLE
add headers for easier CSV reading

### ISSUE THREAD

**Issue by xzhou99** [bstabler/TransportationNetworks#15]

**Comment by pedrocamargo** [comment]
@bstabler , isn't this solved by the change I made recently (including the code)?

**Comment by bstabler** [comment]
See @pedrocamargo Python [script](https://github.com/bstabler/TransportationNetworks/blob/master/_scripts/parsing%20networks.ipynb) for parsing network

**Comment by pedrocamargo** [comment]
Can we close this issue after @chkwon adds the Julia scripts?

**Comment by chkwon** [comment]
I'll soon work on it.
