### ISSUE TITLE
Node Coordinates in Anaheim Network

### ISSUE THREAD

**Issue by 000Justin000** [bstabler/TransportationNetworks#19]
Hello,

I find this repo very useful for my research. I am wondering if you can provide the node coordinates in Anaheim network? If that is not available, I am wondering if there is some extra metadata you have about this network that can help getting those coordinate? We can make it publicly available afterwards.

Thanks,
Junteng

**Comment by bargera** [comment]
All the information I have is on the website. Sorry.

**Comment by alexdawn** [comment]
the map.pdf has the zone coordinates and it would be quite the puzzle to determine the rest of the node ids from the topology of the links.

If you can contact Marco Nie, he produced the map which must have some form of coordinates

**Comment by bstabler** [comment]
Feel free to contact him and see if you can get the data.  Thanks

**Comment by bargera** [comment]
Hi Ben,

This thread came to me in a way that I don't manage to interpret, perhaps
because I am missing the context. I assume that there is no need in my
involvement, but if there is, please let me know what this is all about.

Hillel

**Comment by alexdawn** [comment]
Thanks I have sent Professor Nie an email with the request.

Do you have the source for where some of the other networks come from?

Austin, Barcelona, Eastern-Massachusetts, Hessen, Symmetrica, Terrassa and Winnipeg 
all lack coordinate information

**Comment by alexdawn** [comment]
Professor Nie gave details of a professor Chen where he had got the map data from
```
Dear Alex,

Sorry for the late reply. The Anaheim network was created more than 20 years ago. I am afraid I don’t have the data anymore.

Regards,
Anthony
```
it might still be possible to regenerate coordinates by using some sort of graphing tool to try and use the network topology and the static image to rebuild the coordinates
