### ISSUE TITLE
OBA algorithm unavailable

### ISSUE THREAD

**Issue by PriyadarshanPatil** [bstabler/TransportationNetworks#21]
Hey Dr. Bargera,

The implementation of OBA seems to be unavailable. Could you please let me know if there's an alternative repo I can look into?

Thank you.

**Comment by bstabler** [comment]
@bargera ?

**Comment by bargera** [comment]
Hi Ben,

I see that there have been quite a few TNTP messages in the last couple of
days. I couldn't really understand what is this all about, and whether any
response from me is needed.

I will be travelling in the next couple of weeks, and I don't know how much
internet access I will have. I hope that if my assistance is needed, it can
wait until I return.

Hillel
