### ISSUE TITLE
Chicago Coordinates incorrect

### ISSUE THREAD

**Issue by alexdawn** [bstabler/TransportationNetworks#23]
![image](https://user-images.githubusercontent.com/12990914/54369530-03772e80-466e-11e9-9b1d-5d3e9660e10e.png)

Following the readme I've tried plotting the nodes with the state plane projection using QGIS: NAD_1983_StatePlane_Illinois_East_FIPS_1201_Feet

however as you can see in the screenshot this is not quite right

**Comment by chkwon** [comment]
I am not an expert in GIS, but is there any chance that they are in different coordinate systems?

**Comment by alexdawn** [comment]
Most likely, I've tried the 8 different Illinois State projections in QGIS and none are right, it can take custom projection parameters. I'm no expert on US systems so there could be others. An EPSG index number would be really useful to know exactly which system was used.

**Comment by bstabler** [comment]
Maybe you need a false easting?

**Comment by hhngo96** [comment]
![Image 1](https://user-images.githubusercontent.com/41299310/59297106-0ec9fe00-8c4d-11e9-9a98-c942951bfd1d.png)
I also have the same issue in arcgis. The red polygon are the City of Chicago itself (plotted from the data given by their official website). I tried the NAD 1927 Illinois State Plane East for this figure (i have tried other as well but it do not work).

**Comment by ililbst** [comment]
If I have real coordinates reading from GPS, how do I upload them to the networks?
