### ISSUE TITLE
link travele time

### ISSUE THREAD

**Issue by yqw-929** [bstabler/TransportationNetworks#28]
According to "Link travel time = free flow time * ( 1 + B * (flow/capacity)^Power )"，where is the data of flow? And does the data of flow equal to 'Austin trips.am''s data? Does flow mean every origin node's numbers?
For example:In 'Austin trips.am', origin 1:  1:0.02,does it mean init node  to term node 's flow is 0.02?

**Comment by practice404** [comment]
@yqw-929 I have the same query, did you got the answer for it?
