### ISSUE TITLE
Missing nodes in a few networks

### ISSUE THREAD

**Issue by tr7544** [bstabler/TransportationNetworks#3]
Some nodes in the Barcelona network are missing. The zones are numbered 1 to 110 but the actual thru node starts at 201 instead of 111. I searched for node 111, 112... in the links file but did not find any link with 111, 112.. as its tail or head node.

The same issue exists in the Winnipeg network as well. The nodes between 148-159 are missing. (I haven't checked the remaining networks.)

Could the contributors correct the data files since most papers would be over-reporting the number of nodes in these networks.

Thanks,
Tarun

**Comment by bstabler** [comment]
@tr7544 - please either post these observations as notes/comments in the relevant networks or prepare corrected data files that we can post. Thanks.
