### ISSUE TITLE
Meaning of the FIRST THRU NODE header

### ISSUE THREAD

**Issue by chrhansk** [bstabler/TransportationNetworks#33]
As mentioned in #29: There is a simple relationship between nodes and zones, that is, a zone is a node. You mention regarding the `FIRST THRU NODE` property:

> An important one is the <FIRST THRU NODE>. In the some networks (like Sioux-Falls) it is equal to 1, indicating that traffic can move through all nodes, including zones. In other networks when traffic is not allow to go through zones, the zones are numbered 1 to n and the <FIRST THRU NODE> is set to n+1.

This suggests the following to me: If `FIRST THRU NODE = 1`, ignore the property, otherwise: The zones 1, ..., n are forbidden, which is to say that no traffic may pass through them. I would assume that this implies that no path of edges in any of the trips is allowed to touch any of the nodes 1,...,n.

Now I looked at the `Anaheim` net file, which specifies the `FIRST THRU NODE` to be [39](https://github.com/bstabler/TransportationNetworks/blob/master/Anaheim/Anaheim_net.tntp#L3), implying that no traffc may pass through nodes 1,...,38.

The problem is that *all* trips in the corresponding [trip file](https://github.com/bstabler/TransportationNetworks/blob/would mean that any path has to contain nodes 1,..., 38.

I therefore think that the `FIRST THRU NODE` excludes nodes from being contained in a path *except* for the origin / destination of the path, hence the `THRU` name. So paths *can* contain forbidden nodes as long as they connect them.

Is this a correct understanding of the  `FIRST THRU NODE` entry?

**Comment by chkwon** [comment]
It concurs with my understanding. 

I think those 'non-thru nodes' represent the center of residential/commercial blocks, while all other 'thru nodes' represent physical intersection of roads.

**Comment by chrhansk** [comment]
Thanks, I appreciate the help
