### ISSUE TITLE
Missing node-zone assignment information

### ISSUE THREAD

**Issue by sharathmn** [bstabler/TransportationNetworks#42]
The Winnipeg dataset has 147 zones and 1052 nodes. How to decipher the node-zone relationship from the data? Demand between zones is provided, but not the node-zone assignment.

Any help in this regard would be greatly appreciated.

**Comment by pedrocamargo** [comment]
@sharathmn In all these instances, the node IDs ARE the zone IDs when they are centroids, so zone 1 is centroid 1.

In (very) simplified terms, if a node is not in the demand matrix, then it is not a centroid.

**Comment by sharathmn** [comment]
@pedrocamargo, this explains the node-zone assignment for 147 nodes. What about the remaining 905 nodes? Which zone do they belong to?

**Comment by pedrocamargo** [comment]
There are no zone polygons associated with these instances, @sharathmn , so there is no way to retrieve that information.  Please refer to the specification of the format.  [https://github.com/bstabler/TransportationNetworks#tntp-data-format](url)

**Comment by pedrocamargo** [comment]
I would recommend closing this issue as it is just a question, @bstabler

**Comment by sharathmn** [comment]
> There are no zone polygons associated with these instances, @sharathmn , so there is no way to retrieve that information. Please refer to the specification of the format. [https://github.com/bstabler/TransportationNetworks#tntp-data-format](url)

Thank you @pedrocamargo for your reply. Its a pity a good dataset remains unusable!

**Comment by pedrocamargo** [comment]
@sharathmn, The dataset use-case is purposefully narrow. In the future, I would recommend expanding on what and WHY you are looking for, as such courtesy is especially welcome when we are talking about voluntary efforts such as this.
