### ISSUE TITLE
Regarding Link Travel Time formula mentioned in the README  section

### ISSUE THREAD

**Issue by omm-prakash** [bstabler/TransportationNetworks#51]
> Link travel time = free flow time * ( 1 + B * (flow/capacity)^Power )

what does `flow` means in the above formula mentioned in the README section, in terms of data columns.

**Comment by pedrocamargo** [comment]
Flow is the total flow on the link (cars, if you will).  This is a really basic concept in transport modelling, so you may want to begin by reading this:  https://tfresource.org/topics/Network_assignment.html

**Comment by omm-prakash** [comment]
But, how to extract the same data from [here](https://github.com/bstabler/TransportationNetworks/blob/master/Chicago-Sketch/ChicagoSketch_net.tntp)

**Comment by pedrocamargo** [comment]
That is the result of the traffic assignment process. You really need to study this subject before asking more questions, or the questions you will be able to ask will make no sense

**Comment by pedrocamargo** [comment]
I am guessing that somebody else taking the same class as you have asked this question before.  https://github.com/bstabler/TransportationNetworks/issues/50

**Comment by pedrocamargo** [comment]
@bstabler , you can just close this issue as question/invalid
